### ISSUE TITLE
Foxpro window closing automatically while running Foxpro2Python

### ISSUE THREAD

**Issue by Act1234** [mwisslead/foxpro2python#3] opened 2019-01-08 16:13 UTC
Hi

As per my earlier request, python implementation done successfully with your help.  Now the issue is, when i open the Visual Foxpro 9 and execute the program from command prompt, several time it is closing foxpro and after that it is working.  How to resolve this.

Also once i ran the program, next time without closing foxpro, if i try to run once again, it is showing hard error "Variable PYEmptyTuple is not found".  How to release memory and restart the process through progamatically?

**Comment by mwisslead** [comment] 2019-01-08 21:39
Can you give a more detailed description of what you are executing? I am unable to reproduce these errors.

**Comment by Act1234** [comment] 2019-01-09 07:56
When i executed sample.prg first time, the visual foxpro screen got closed.  Then once again if i open foxpro and execute the sample.prg, then it is working.  This is the case for foxpro closing.

When i successfully ran the application and back to foxpro command prompt.  I am trying to rerun the application once again.  In this case i am getting the following error and screen shot attached for the same..
"Variable PYEMPTYTUPLE not found".
![error](https://user-images.githubusercontent.com/45997011/50884866-196c3700-1412-11e9-8964-aaaf9b6c4bbf.PNG)

**Comment by Act1234** [comment] 2019-01-09 08:08
Now I have 2 Python module.  Based on selection in VFP i need to execute the selected module.  For that i written the following code in __Init__.py file. While executing the process, system showing the following error.
![error1](https://user-images.githubusercontent.com/45997011/50885100-c47cf080-1412-11e9-9cce-48541ad31817.PNG)


Attached zip file with this.  Main file is sample.prg
[test.zip](https://github.com/mwisslead/foxpro2python/files/2739869/test.zip)

**Comment by mwisslead** [comment] 2019-01-09 13:36
Are you using your modified example_module when running the tests.prg? If so, I think I might be able to reproduce the problem. I will let you know when I am able to do more testing.

The PyEmptyTuple problem must be from running a "CLEAR MEMORY" command or something similar. There is a stop_python function in python.prg you can call but it has some design flaws that haven't been addressed due to not being used normally. I would recommend running "CLEAR DLLS" which should solve the problem.

The valueerror message isn't really related to foxpro2python. It is an error being reported from python. This is because, in the "if (Choice == 1 ):" line, Choice is a pandas Series and not a single value.

**Comment by Act1234** [comment] 2019-01-10 08:06
Can we install Tensorflow and keras in 32 bit windows 10 system? My python version is Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32

**Comment by mwisslead** [comment] 2019-01-10 14:16
Looks to me like tensorflow only has pypi packages for 64 bit. Anything 32-bit should work though.

**Comment by mwisslead** [comment] 2019-01-10 14:46
I have not been able to produce any problem that causes foxpro to close. Can you confirm which line of python.prg foxpro closes on? I'm assuming line 492 (Py_Initialize()). Also can you give more details about windows and foxpro versions?

After testing the PyEmptyTuple is not found error with your code I wouldn't recommend running clear all while using foxpro2python since it uses public variables to keep track of things. I will try to fix this issue in the future.

**Comment by Act1234** [comment] 2019-01-11 09:00
Yes correct.  When Py_initalize() getting executed.  Refer the following screenshot.
![pyerror](https://user-images.githubusercontent.com/45997011/51023556-32f5b600-15ad-11e9-8dc6-268ddfee2e33.PNG)

For the error "PyEmptyTuple is not found" error, i added clear dlls starting of my program.  Then also it appears when i execute next time without closing forxpro.

I am using Windows 10 Pro and Foxpro 9.0 with SP2

**Comment by Act1234** [comment] 2019-01-16 12:47
Hi

Any update

**Comment by mwisslead** [comment] 2019-01-16 18:37
I added code that fixes the PyEmptyTuple problem.

**Comment by mwisslead** [comment] 2019-01-16 22:09
I think I may have solved the problem. Go ahead and try out the lastest version.

**Comment by mwisslead** [comment] 2019-01-26 21:24
Going to close this since I believe it's fixed.

**Closed as completed by mwisslead** 2019-01-26 21:24 UTC
